version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    entrypoint: bin/maildev -w 1080 -s 1025

volumes:
  postgres:
    name: nest-db
