version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: ../prisma
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      DB_HOST: postgres
      DB_URL: ${DB_URL}

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
